# EMPLOYEE DATASET

### EMPLOYEE DATASET

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.DataFrame({"name":["vishwas",'Uma',"Tanvi","Shraddha","monika","Ruchika"],
                "Age":[23,23,34,45,56,34],
                "Designation":["HwR","CO","CR","HR",np.nan,"Employee"],
                "Salary":[230000000,3400000,560000,450000,43000,9000]})
df

       name  Age Designation     Salary
0   vishwas   23         HwR  230000000
1       Uma   23          CO    3400000
2     Tanvi   34          CR     560000
3  Shraddha   45          HR     450000
4    monika   56         NaN      43000
5   Ruchika   34    Employee       9000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         6 non-null      object
 1   Age          6 non-null      int64
 2   Designation  5 non-null      object
 3   Salary       6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [ ]:
df.describe()

             Age        Salary
count   6.000000  6.000000e+00
mean   35.833333  3.907700e+07
std    12.859497  9.354144e+07
min    23.000000  9.000000e+03
25%    25.750000  1.447500e+05
50%    34.000000  5.050000e+05
75%    42.250000  2.690000e+06
max    56.000000  2.300000e+08

In [ ]:
df.describe(include="object")

           name Designation
count         6           5
unique        6           5
top     vishwas         HwR
freq          1           1

In [ ]:
df.describe(include="all")

           name        Age Designation        Salary
count         6   6.000000           5  6.000000e+00
unique        6        NaN           5           NaN
top     vishwas        NaN         HwR           NaN
freq          1        NaN           1           NaN
mean        NaN  35.833333         NaN  3.907700e+07
std         NaN  12.859497         NaN  9.354144e+07
min         NaN  23.000000         NaN  9.000000e+03
25%         NaN  25.750000         NaN  1.447500e+05
50%         NaN  34.000000         NaN  5.050000e+05
75%         NaN  42.250000         NaN  2.690000e+06
max         NaN  56.000000         NaN  2.300000e+08

In [ ]:
df

       name  Age Designation     Salary
0   vishwas   23         HwR  230000000
1       Uma   23          CO    3400000
2     Tanvi   34          CR     560000
3  Shraddha   45          HR     450000
4    monika   56         NaN      43000
5   Ruchika   34    Employee       9000

In [ ]:
df.drop("Salary",axis=1)

       name  Age Designation
0   vishwas   23         HwR
1       Uma   23          CO
2     Tanvi   34          CR
3  Shraddha   45          HR
4    monika   56         NaN
5   Ruchika   34    Employee

In [ ]:
df.drop(2)

       name  Age Designation     Salary
0   vishwas   23         HwR  230000000
1       Uma   23          CO    3400000
3  Shraddha   45          HR     450000
4    monika   56         NaN      43000
5   Ruchika   34    Employee       9000

In [ ]:
df.isnull().sum()

name           0
Age            0
Designation    1
Salary         0
dtype: int64

In [ ]:
df.isna().count()

name           6
Age            6
Designation    6
Salary         6
dtype: int64

In [ ]:
df.dropna()

       name  Age Designation     Salary
0   vishwas   23         HwR  230000000
1       Uma   23          CO    3400000
2     Tanvi   34          CR     560000
3  Shraddha   45          HR     450000
5   Ruchika   34    Employee       9000

axis=1row

axis=0column