# STUDENT RESULT

### STUDENT RESULT

In [ ]:
import pandas as pd
import matplotlib as plt

In [ ]:
data={"Name":['A','B',"C","D"],
      "Marks":[80,30,70,None]}
df=pd.DataFrame(data)
df.isnull().sum()
df['Marks'].fillna(0)
df["Marks"].fillna(df["Marks"].mean())
df.dropna()

  Name  Marks
0    A   80.0
1    B   30.0
2    C   70.0

In [ ]:
df

  Name  Marks
0    A   80.0
1    B   30.0
2    C   70.0
3    D    NaN

In [ ]:
df.sort_values("Marks")

  Name  Marks
1    B   30.0
2    C   70.0
0    A   80.0
3    D    NaN

In [ ]:
df.sort_values("Marks",ascending=False)

  Name  Marks
0    A   80.0
2    C   70.0
1    B   30.0
3    D    NaN

In [ ]:
df.sort_values("Marks",ascending=False)

  Name  Marks
0    A   80.0
2    C   70.0
1    B   30.0
3    D    NaN

In [ ]:
df["Marks"].nunique()

3

In [ ]:
df["Marks"].unique()

array([80., 30., 70., nan])

In [ ]:
df

  Name  Marks
0    A   80.0
1    B   30.0
2    C   70.0
3    D    NaN

In [ ]:
df["Marks"].value_counts()

Marks
80.0    1
30.0    1
70.0    1
Name: count, dtype: int64