# STUDENTS DATA

### STUDENTS DATA

In [ ]:
import pandas as pd

In [ ]:

s=pd.Series([1,2,3,4,5])
print(s)
df=pd.DataFrame(
                {"Name":['A','B','C',"D"],
                 "Age":[18,20,21,17],
                "Marks":[80,90,70,94]
                })
print(df)
print(df.columns)
df["Name"]
df[["Age","Marks"]]
df[df["Age"]>18]
df[:3]

0    1
1    2
2    3
3    4
4    5
dtype: int64
  Name  Age  Marks
0    A   18     80
1    B   20     90
2    C   21     70
3    D   17     94

  Name  Age  Marks
0    A   18     80
1    B   20     90
2    C   21     70

In [ ]:
df.iloc[2]#print third row

Name      C
Age      21
Marks    70
Name: 2, dtype: object

In [ ]:
df.iloc[0:2]

  Name  Age  Marks
0    A   18     80
1    B   20     90

In [ ]:
df.loc[0,"Name"]

'A'

In [ ]:
df

  Name  Age  Marks
0    A   18     80
1    B   20     90
2    C   21     70
3    D   17     94

In [ ]:
df.iloc[0:1]
df.loc[2,"Age"]
df.iloc[:2,0:1]
df.loc[:,"Marks"]
df[df["Marks"]>80]

  Name  Age  Marks
1    B   20     90
3    D   17     94

In [ ]:
df["Grade"]=["B",'A','C','A']
print(df)

  Name  Age  Marks Grade
0    A   18     80     B
1    B   20     90     A
2    C   21     70     C
3    D   17     94     A

In [ ]:
df["Bonus"]=df["Marks"]+5
df

  Name  Age  Marks Grade  Bonus
0    A   18     80     B     85
1    B   20     90     A     95
2    C   21     70     C     75
3    D   17     94     A     99

In [ ]:
df.drop("Bonus",axis=1,inplace=True)
print(df)

  Name  Age  Marks Grade
0    A   18     80     B
1    B   20     90     A
2    C   21     70     C
3    D   17     94     A

In [ ]:
df

  Name  Age  Marks Grade
0    A   18     80     B
1    B   20     90     A
2    C   21     70     C
3    D   17     94     A

In [ ]:
df["City"]=["Delhi","Mumbai","Agra","Indore"]
df
df["Total marks"]=df["Marks"]+10
df
df.drop("City",axis=1,inplace=True)
df['Pass']=df["Marks"].apply(lambda x: "Yes" if x>75 else "No")

df

  Name  Age  Marks Grade  Total marks Pass
0    A   18     80     B           90  Yes
1    B   20     90     A          100  Yes
2    C   21     70     C           80   No
3    D   17     94     A          104  Yes

In [ ]:

data={"Name":["A","B","C","D"],
      "Marks":[80,None,70,None]}
df=pd.DataFrame(data)
print(df)

  Name  Marks
0    A   80.0
1    B    NaN
2    C   70.0
3    D    NaN

In [ ]:
df.isnull()

    Name  Marks
0  False  False
1  False   True
2  False  False
3  False   True

In [ ]:
df.isnull().sum()

Name     0
Marks    2
dtype: int64

In [ ]:
df["Marks"].fillna(0)

0    80.0
1     0.0
2    70.0
3     0.0
Name: Marks, dtype: float64

In [ ]:
df["Marks"].fillna(df["Marks"].mean())

0    80.0
1    75.0
2    70.0
3    75.0
Name: Marks, dtype: float64

In [ ]:
df.dropna()

  Name  Marks
0    A   80.0
2    C   70.0