# Pandas Practice

In [ ]:
import pandas as pd
import numpy as np

### ADVERTISING

In [12]:
df = pd.read_csv(
    r"\\wsl.localhost\Ubuntu\home\vishwas_sharma\Documents\Exploratory_Data_Analysis_using_python_portfolio\Datasets\Advertising.csv"
)
print(df)

     Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [13]:
print(df.head())

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [14]:
print(df.tail())

     Unnamed: 0     TV  Radio  Newspaper  Sales
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

In [15]:
df.columns

Index(['Unnamed: 0', 'TV', 'Radio', 'Newspaper', 'Sales'], dtype='str')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  200 non-null    int64
 1   TV          200 non-null    float64
 2   Radio       200 non-null    float64
 3   Newspaper   200 non-null    float64
 4   Sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

In [17]:
df.describe()

       Unnamed: 0          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [18]:
df["TV"]

0      230.1
1       44.5
2       17.2
3      151.5
4      180.8
       ...
195     38.2
196     94.2
197    177.0
198    283.6
199    232.1
Name: TV, Length: 200, dtype: float64

In [19]:
df[["TV","Sales"]]

        TV  Sales
0    230.1   22.1
1     44.5   10.4
2     17.2    9.3
3    151.5   18.5
4    180.8   12.9
..     ...    ...
195   38.2    7.6
196   94.2    9.7
197  177.0   12.8
198  283.6   25.5
199  232.1   13.4

[200 rows x 2 columns]

In [20]:
df.iloc[0]

Unnamed: 0      1.0
TV            230.1
Radio          37.8
Newspaper      69.2
Sales          22.1
Name: 0, dtype: float64

In [21]:
df[df["radio"]>40]

KeyError: 'radio'

### STUDENTS DATA

In [ ]:
import pandas as pd
s=pd.Series([1,2,3,4,5])
print(s)
df=pd.DataFrame(
                {"Name":['A','B','C',"D"],
                 "Age":[18,20,21,17],
                "Marks":[80,90,70,94]
                })
print(df)
df.columns
df["Name"]
df[["Age","Marks"]]
df[df["Age"]>18]
df[:3]

0    1
1    2
2    3
3    4
4    5
dtype: int64
  Name  Age  Marks
0    A   18     80
1    B   20     90
2    C   21     70
3    D   17     94

  Name  Age  Marks
0    A   18     80
1    B   20     90
2    C   21     70

In [ ]:
df.iloc[2]#print third row

Name      C
Age      21
Marks    70
Name: 2, dtype: object

In [ ]:
df.iloc[0:2]

  Name  Age  Marks
0    A   18     80
1    B   20     90

In [ ]:
df.loc[0,"Name"]

'A'

In [ ]:
df

  Name  Age  Marks
0    A   18     80
1    B   20     90
2    C   21     70
3    D   17     94

In [ ]:
df.iloc[0:1]
df.loc[2,"Age"]
df.iloc[:2,0:1]
df.loc[:,"Marks"]
df[df["Marks"]>80]

  Name  Age  Marks
1    B   20     90
3    D   17     94

In [ ]:
df["Grade"]=["B",'A','C','A']
print(df)

  Name  Age  Marks Grade
0    A   18     80     B
1    B   20     90     A
2    C   21     70     C
3    D   17     94     A

In [ ]:
df["Bonus"]=df["Marks"]+5
df

  Name  Age  Marks Grade  Bonus
0    A   18     80     B     85
1    B   20     90     A     95
2    C   21     70     C     75
3    D   17     94     A     99

In [ ]:
df.drop("Bonus",axis=1,inplace=True)
print(df)

  Name  Age  Marks Grade
0    A   18     80     B
1    B   20     90     A
2    C   21     70     C
3    D   17     94     A

In [ ]:
df

  Name  Age  Marks Grade
0    A   18     80     B
1    B   20     90     A
2    C   21     70     C
3    D   17     94     A

In [ ]:
df["City"]=["Delhi","Mumbai","Agra","Indore"]

df["Total marks"]=df["Marks"]+10

df.drop("City",axis=1,inplace=True)
df['Pass']=df["Marks"].apply(lambda x: "Yes" if x>75 else "No")

df

  Name  Age  Marks Grade  Total marks Pass
0    A   18     80     B           90  Yes
1    B   20     90     A          100  Yes
2    C   21     70     C           80   No
3    D   17     94     A          104  Yes

In [ ]:

data={"Name":["A","B","C","D"],
      "Marks":[80,None,70,None]}
df=pd.DataFrame(data)
print(df)

  Name  Marks
0    A   80.0
1    B    NaN
2    C   70.0
3    D    NaN

In [ ]:
df.isnull()

    Name  Marks
0  False  False
1  False   True
2  False  False
3  False   True

In [ ]:
df.isnull().sum()

Name     0
Marks    2
dtype: int64

In [ ]:
df["Marks"].fillna(0)

0    80.0
1     0.0
2    70.0
3     0.0
Name: Marks, dtype: float64

In [ ]:
df["Marks"].fillna(df["Marks"].mean())

0    80.0
1    75.0
2    70.0
3    75.0
Name: Marks, dtype: float64

In [ ]:
df.dropna()

  Name  Marks
0    A   80.0
2    C   70.0

### STUDENT RESULT

In [ ]:
data={"Name":['A','B',"C","D"],
      "Marks":[80,30,70,None]}
df=pd.DataFrame(data)

df.isnull().sum()
df['Marks'].fillna(0)
df["Marks"].fillna(df["Marks"].mean())
df.dropna()

  Name  Marks
0    A   80.0
1    B   30.0
2    C   70.0

In [ ]:
df

  Name  Marks
0    A   80.0
1    B   30.0
2    C   70.0
3    D    NaN

In [ ]:
df.sort_values("Marks")

  Name  Marks
1    B   30.0
2    C   70.0
0    A   80.0
3    D    NaN

In [ ]:
df.sort_values("Marks",ascending=False)

  Name  Marks
0    A   80.0
2    C   70.0
1    B   30.0
3    D    NaN

In [ ]:
df.sort_values("Marks",ascending=False)

  Name  Marks
0    A   80.0
2    C   70.0
1    B   30.0
3    D    NaN

In [ ]:
df["Marks"].nunique()

3

In [ ]:
df["Marks"].unique()

array([80., 30., 70., nan])

In [ ]:
df

  Name  Marks
0    A   80.0
1    B   30.0
2    C   70.0
3    D    NaN

In [ ]:
df["Marks"].value_counts()

Marks
80.0    1
30.0    1
70.0    1
Name: count, dtype: int64

### STUDENTS RESULT 0.2

In [ ]:
data={
    'Name':['A','B','C','D','E'],
    "Marks":[80,90,70,80,60],
    "City":["Delhi","Mumbai","Delhi","Pune","Delhi"]
    }
df=pd.DataFrame(data)
df

  Name  Marks    City
0    A     80   Delhi
1    B     90  Mumbai
2    C     70   Delhi
3    D     80    Pune
4    E     60   Delhi

In [ ]:
df.sort_values('Marks')

  Name  Marks    City
4    E     60   Delhi
2    C     70   Delhi
3    D     80    Pune
0    A     80   Delhi
1    B     90  Mumbai

In [ ]:
df.sort_values('Marks',ascending=False)

  Name  Marks    City
1    B     90  Mumbai
0    A     80   Delhi
3    D     80    Pune
2    C     70   Delhi
4    E     60   Delhi

In [ ]:
df['City'].unique()

array(['Delhi', 'Mumbai', 'Pune'], dtype=object)

In [ ]:
df["City"].nunique()

3

In [ ]:
df["Marks"].value_counts()

Marks
80    2
90    1
70    1
60    1
Name: count, dtype: int64

In [ ]:
df["City"].value_counts()

City
Delhi     3
Mumbai    1
Pune      1
Name: count, dtype: int64

In [ ]:
df.groupby("City")

In [ ]:
df

  Name  Marks    City
0    A     80   Delhi
1    B     90  Mumbai
2    C     70   Delhi
3    D     80    Pune
4    E     60   Delhi

In [ ]:
df.groupby('City')["Marks"].mean()

City
Delhi     70.0
Mumbai    90.0
Pune      80.0
Name: Marks, dtype: float64

In [ ]:
df.groupby('City')['Marks'].sum()

City
Delhi     210
Mumbai     90
Pune       80
Name: Marks, dtype: int64

In [ ]:
df.groupby("City")["Name"].count()

City
Delhi     3
Mumbai    1
Pune      1
Name: Name, dtype: int64

In [ ]:
df['City'].value_counts()

City
Delhi     3
Mumbai    1
Pune      1
Name: count, dtype: int64

In [ ]:
df.groupby("City")["Marks"].agg(['mean','max','min',"count"])

        mean  max  min  count
City
Delhi   70.0   80   60      3
Mumbai  90.0   90   90      1
Pune    80.0   80   80      1

In [ ]:
df.groupby(["City",'Marks']).count()

              Name
City   Marks
Delhi  60        1
       70        1
       80        1
Mumbai 90        1
Pune   80        1

In [ ]:
df

  Name  Marks    City
0    A     80   Delhi
1    B     90  Mumbai
2    C     70   Delhi
3    D     80    Pune
4    E     60   Delhi

In [ ]:
df.groupby("City")["Marks"].mean()
df.groupby("City")["Marks"].max()
df.groupby("City")["Marks"].min()
df.groupby("City").count()
df.groupby("City")["Marks"].agg(['mean',"max","min"])
df.groupby("City")['Marks'].sum()

City
Delhi     210
Mumbai     90
Pune       80
Name: Marks, dtype: int64

### ADVERTISING 0.2

In [ ]:
df=pd.read_csv(r"C:\Users\vishw\Advertising.csv")
df

     Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [ ]:
df.head()
df.info()
df.describe()
df.corr()
df.corr()['sales']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  200 non-null    int64
 1   TV          200 non-null    float64
 2   radio       200 non-null    float64
 3   newspaper   200 non-null    float64
 4   sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

Unnamed: 0   -0.051616
TV            0.782224
radio         0.576223
newspaper     0.228299
sales         1.000000
Name: sales, dtype: float64

In [ ]:
df.sort_values("TV",ascending=False)
df["TV"].unique()
df["TV"].nunique()
df["TV"].value_counts()

TV
17.2     2
199.8    2
240.1    2
237.4    2
177.0    2
        ..
149.7    1
38.2     1
94.2     1
283.6    1
232.1    1
Name: count, Length: 190, dtype: int64

In [ ]:
df.rename(columns={'sales':"Sales"},inplace=True)

In [ ]:
df

     Unnamed: 0     TV  radio  newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [ ]:
df["radio"]=df['radio'].astype(int)

In [ ]:
df

     Unnamed: 0     TV  radio  newspaper  Sales
0             1  230.1     37       69.2   22.1
1             2   44.5     39       45.1   10.4
2             3   17.2     45       69.3    9.3
3             4  151.5     41       58.5   18.5
4             5  180.8     10       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2      3       13.8    7.6
196         197   94.2      4        8.1    9.7
197         198  177.0      9        6.4   12.8
198         199  283.6     42       66.2   25.5
199         200  232.1      8        8.7   13.4

[200 rows x 5 columns]

In [ ]:
df["radio"].sum()

np.int64(4558)

In [ ]:
df["TV"]=df['TV'].apply(lambda x:"Too high" if x>100 else "Too Low")

In [ ]:
df

     Unnamed: 0        TV  radio  newspaper  Sales
0             1  Too high     37       69.2   22.1
1             2   Too Low     39       45.1   10.4
2             3   Too Low     45       69.3    9.3
3             4  Too high     41       58.5   18.5
4             5  Too high     10       58.4   12.9
..          ...       ...    ...        ...    ...
195         196   Too Low      3       13.8    7.6
196         197   Too Low      4        8.1    9.7
197         198  Too high      9        6.4   12.8
198         199  Too high     42       66.2   25.5
199         200  Too high      8        8.7   13.4

[200 rows x 5 columns]

In [ ]:
df["newspaper"].sort_values(ascending=False)

16     114.0
101    100.9
75      89.4
165     84.8
118     79.2
       ...
42       1.8
139      1.7
8        1.0
65       0.9
33       0.3
Name: newspaper, Length: 200, dtype: float64

In [ ]:
df["newspaper"].unique()
df["newspaper"].value_counts()
df.rename(columns={"Sales":"sales"},inplace=True)
df["Performance"]=df["sales"].apply(lambda x: "Well" if x>14 else "Need Improvement")
df["sales"].apply(lambda x: x+10)

0      32.1
1      20.4
2      19.3
3      28.5
4      22.9
       ...
195    17.6
196    19.7
197    22.8
198    35.5
199    23.4
Name: sales, Length: 200, dtype: float64

In [ ]:
df["sales"].describe()

count    200.000000
mean      14.022500
std        5.217457
min        1.600000
25%       10.375000
50%       12.900000
75%       17.400000
max       27.000000
Name: sales, dtype: float64

In [ ]:
df1=pd.DataFrame({"id":[1,6,3],
                  "name":["A","B","C"]}
                  )
df2=pd.DataFrame({"id":[1,2,4],
                  "marks":[80,90,70]}
                  )

In [ ]:
df=pd.merge(df1,df2,on="id")
print(df)

   id name  marks
0   1    A     80

In [ ]:
pd.merge(df1,df2,on="id",how="left")

   id name  marks
0   1    A   80.0
1   6    B    NaN
2   3    C    NaN

In [ ]:
pd.merge(df1,df2,on="id",how="right")

   id name  marks
0   1    A     80
1   2  NaN     90
2   4  NaN     70

In [ ]:
pd.merge(df1,df2,how="outer")

   id name  marks
0   1    A   80.0
1   2  NaN   90.0
2   3    C    NaN
3   4  NaN   70.0
4   6    B    NaN

In [ ]:
pd.merge(df1,df2,how="inner")

   id name  marks
0   1    A     80

In [ ]:
data={'name':["A","B","C","A","B"],
      "marks":[80,90,70,80,90]}
df=pd.DataFrame(data)
print(df)

  name  marks
0    A     80
1    B     90
2    C     70
3    A     80
4    B     90

In [ ]:
df.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [ ]:
df.drop_duplicates(inplace=True)
df

  name  marks
0    A     80
1    B     90
2    C     70

In [ ]:
df.drop_duplicates(subset="name")

  name  marks
0    A     80
1    B     90
2    C     70

In [ ]:
data={"name":["ram   ","Shyam","Mohan","raM"]}
df=pd.DataFrame(data)
df

     name
0  ram
1   Shyam
2   Mohan
3     raM

In [ ]:
df["name"]=df["name"].str.lower()
df

     name
0  ram
1   shyam
2   mohan
3     ram

In [ ]:
df["name"]=df["name"].str.strip()
df

    name
0    ram
1  shyam
2  mohan
3    ram

In [ ]:
df['name']=df['name'].str.strip().str.lower()
df

    name
0    ram
1  shyam
2  mohan
3    ram

In [ ]:
df['name'].str.contains('ram')

df

    name
0    ram
1  shyam
2  mohan
3    ram

In [ ]:
data={"name":["Ram",'Shyam',"RAM",'Mohan',"shyam"],
      "marks":[80,90,70,60,40]}
df=pd.DataFrame(data)
df

    name  marks
0    Ram     80
1  Shyam     90
2    RAM     70
3  Mohan     60
4  shyam     40

In [ ]:
df.drop_duplicates()
df["name"]=df['name'].str.strip()
df['name']=df['name'].str.lower()
df['name'].unique()
df["name"].str.contains("ram")
df["name"].replace("ram","राम")

0      राम
1    shyam
2      राम
3    mohan
4    shyam
Name: name, dtype: object

In [ ]:
df

    name  marks
0    ram     80
1  shyam     90
2    ram     70
3  mohan     60
4  shyam     40

In [ ]:
df=pd.read_csv(r"C:\Users\vishw\Advertising.csv")

df

     Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [ ]:
df[df["sales"]>10]

     Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
6             7   57.5   32.8       23.5   11.8
..          ...    ...    ...        ...    ...
193         194  166.8   42.0        3.6   19.6
194         195  149.7   35.6        6.0   17.3
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[155 rows x 5 columns]

### DATE AND TIME

In [ ]:
data={"date":["2024-01-01","2024-02-15","2024-03-10"]}
df=pd.DataFrame(data)
df

         date
0  2024-01-01
1  2024-02-15
2  2024-03-10

In [ ]:
df['date']=pd.to_datetime(df["date"])
df

        date
0 2024-01-01
1 2024-02-15
2 2024-03-10

In [ ]:
df["year"]=df["date"].dt.year
df

        date  year
0 2024-01-01  2024
1 2024-02-15  2024
2 2024-03-10  2024

In [ ]:
df["month"]=df['date'].dt.month
df

        date  year  month
0 2024-01-01  2024      1
1 2024-02-15  2024      2
2 2024-03-10  2024      3

In [ ]:
df["day_name"]=df["date"].dt.day_name
df

        date  year  month                                           day_name
0 2024-01-01  2024      1  <bound method PandasDelegate._add_delegate_acc...
1 2024-02-15  2024      2  <bound method PandasDelegate._add_delegate_acc...
2 2024-03-10  2024      3  <bound method PandasDelegate._add_delegate_acc...

In [ ]:
df[df['date']>"2024-02-01"]

        date  year  month                                           day_name
1 2024-02-15  2024      2  <bound method PandasDelegate._add_delegate_acc...
2 2024-03-10  2024      3  <bound method PandasDelegate._add_delegate_acc...

In [ ]:
df["next_date"]=df["date"].shift(-1)
df["diff"]=df["next_date"]-df["date"]
df

,date,year,month,day_name,next_date,diff
0,2024-01-01,2024,1,<bound method PandasDelegate._add_delegate_acc...,2024-02-15,45 days
1,2024-02-15,2024,2,<bound method PandasDelegate._add_delegate_acc...,2024-03-10,24 days
2,2024-03-10,2024,3,<bound method PandasDelegate._add_delegate_acc...,NaT,NaT

In [ ]:
df.sort_values("date")

,date,year,month,day_name,next_date,diff
0,2024-01-01,2024,1,<bound method PandasDelegate._add_delegate_acc...,2024-02-15,45 days
1,2024-02-15,2024,2,<bound method PandasDelegate._add_delegate_acc...,2024-03-10,24 days
2,2024-03-10,2024,3,<bound method PandasDelegate._add_delegate_acc...,NaT,NaT

In [ ]:
date={"date":["2024-01-01","2024-01-10","2024-02-05","2024-03-20"]}
df=pd.DataFrame(data)
df

         date
0  2024-01-01
1  2024-02-15
2  2024-03-10

In [ ]:
df['date']=pd.to_datetime(df["date"])
df

        date
0 2024-01-01
1 2024-02-15
2 2024-03-10

In [ ]:
df['year']=df['date'].dt.year
df

        date  year
0 2024-01-01  2024
1 2024-02-15  2024
2 2024-03-10  2024

In [ ]:
df['month']=df["date"].dt.month
df

        date  year  month
0 2024-01-01  2024      1
1 2024-02-15  2024      2
2 2024-03-10  2024      3

In [ ]:
df['day_name']=df['date'].dt.day_name
df

        date  year  month                                           day_name
0 2024-01-01  2024      1  <bound method PandasDelegate._add_delegate_acc...
1 2024-02-15  2024      2  <bound method PandasDelegate._add_delegate_acc...
2 2024-03-10  2024      3  <bound method PandasDelegate._add_delegate_acc...

In [ ]:
df[df['date']>"2024-01-15"]

        date  year  month                                           day_name
1 2024-02-15  2024      2  <bound method PandasDelegate._add_delegate_acc...
2 2024-03-10  2024      3  <bound method PandasDelegate._add_delegate_acc...

In [ ]:
df['next_day']=df['date'].shift(-1)
df['diff']=df["next_day"]-df['date']
df

,date,year,month,day_name,next_day,diff
0,2024-01-01,2024,1,<bound method PandasDelegate._add_delegate_acc...,2024-02-15,45 days
1,2024-02-15,2024,2,<bound method PandasDelegate._add_delegate_acc...,2024-03-10,24 days
2,2024-03-10,2024,3,<bound method PandasDelegate._add_delegate_acc...,NaT,NaT

In [ ]:
import pandas as pd

In [ ]:
s=pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
print(s.name)

None

In [ ]:
s.name="marks"
s

0    10
1    20
2    30
3    40
Name: marks, dtype: int64

In [ ]:
print(s.name)

marks

In [ ]:
s=pd.Series([1,2,3,4,5,"isha"],name="marks")

In [ ]:
s

0       1
1       2
2       3
3       4
4       5
5    isha
Name: marks, dtype: object

In [ ]:
s.values

array([1, 2, 3, 4, 5, 'isha'], dtype=object)

In [ ]:
s.iloc[[1,2,3]]

1    2
2    3
3    4
Name: marks, dtype: object

In [ ]:
s.dtype

dtype('O')

In [ ]:
index=["Uma","Vishwas","Vedik","Jatin","Jayas","Kirtan"]
s.index=index
s

Uma           1
Vishwas       2
Vedik         3
Jatin         4
Jayas         5
Kirtan     isha
Name: marks, dtype: object

In [ ]:
s.loc["Uma":"Vishwas"]

Uma        1
Vishwas    2
Name: marks, dtype: object

In [ ]:
dict1={"name":"isha","dept":"IT","age":25,"salary":10000}

In [ ]:
se=pd.Series(dict1,name="data")
se

name       isha
dept         IT
age          25
salary    10000
Name: data, dtype: object

### EMPLOYEE DATASET

In [ ]:
df=pd.DataFrame({"name":["vishwas",'Uma',"Tanvi","Shraddha","monika","Ruchika"],
                "Age":[23,23,34,45,56,34],
                "Designation":["HwR","CO","CR","HR",np.nan,"Employee"],
                "Salary":[230000000,3400000,560000,450000,43000,9000]})
df

       name  Age Designation     Salary
0   vishwas   23         HwR  230000000
1       Uma   23          CO    3400000
2     Tanvi   34          CR     560000
3  Shraddha   45          HR     450000
4    monika   56         NaN      43000
5   Ruchika   34    Employee       9000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         6 non-null      object
 1   Age          6 non-null      int64
 2   Designation  5 non-null      object
 3   Salary       6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [ ]:
df.describe()

             Age        Salary
count   6.000000  6.000000e+00
mean   35.833333  3.907700e+07
std    12.859497  9.354144e+07
min    23.000000  9.000000e+03
25%    25.750000  1.447500e+05
50%    34.000000  5.050000e+05
75%    42.250000  2.690000e+06
max    56.000000  2.300000e+08

In [ ]:
df.describe(include="object")

           name Designation
count         6           5
unique        6           5
top     vishwas         HwR
freq          1           1

In [ ]:
df.describe(include="all")

           name        Age Designation        Salary
count         6   6.000000           5  6.000000e+00
unique        6        NaN           5           NaN
top     vishwas        NaN         HwR           NaN
freq          1        NaN           1           NaN
mean        NaN  35.833333         NaN  3.907700e+07
std         NaN  12.859497         NaN  9.354144e+07
min         NaN  23.000000         NaN  9.000000e+03
25%         NaN  25.750000         NaN  1.447500e+05
50%         NaN  34.000000         NaN  5.050000e+05
75%         NaN  42.250000         NaN  2.690000e+06
max         NaN  56.000000         NaN  2.300000e+08

In [ ]:
df

       name  Age Designation     Salary
0   vishwas   23         HwR  230000000
1       Uma   23          CO    3400000
2     Tanvi   34          CR     560000
3  Shraddha   45          HR     450000
4    monika   56         NaN      43000
5   Ruchika   34    Employee       9000

In [ ]:
df.drop("Salary",axis=1)

       name  Age Designation
0   vishwas   23         HwR
1       Uma   23          CO
2     Tanvi   34          CR
3  Shraddha   45          HR
4    monika   56         NaN
5   Ruchika   34    Employee

In [ ]:
df.drop(2)

       name  Age Designation     Salary
0   vishwas   23         HwR  230000000
1       Uma   23          CO    3400000
3  Shraddha   45          HR     450000
4    monika   56         NaN      43000
5   Ruchika   34    Employee       9000

In [ ]:
df.isnull().sum()

name           0
Age            0
Designation    1
Salary         0
dtype: int64

In [ ]:
df.isna().count()

name           6
Age            6
Designation    6
Salary         6
dtype: int64

In [ ]:
df.dropna()

       name  Age Designation     Salary
0   vishwas   23         HwR  230000000
1       Uma   23          CO    3400000
2     Tanvi   34          CR     560000
3  Shraddha   45          HR     450000
5   Ruchika   34    Employee       9000

axis=1row

axis=0column