# Pandas Date and Time

### DATE AND TIME

In [ ]:
import pandas as pd

In [ ]:
data={"date":["2024-01-01","2024-02-15","2024-03-10"]}
df=pd.DataFrame(data)
df

         date
0  2024-01-01
1  2024-02-15
2  2024-03-10

In [ ]:
df['date']=pd.to_datetime(df["date"])
df

        date
0 2024-01-01
1 2024-02-15
2 2024-03-10

In [ ]:
df["year"]=df["date"].dt.year
df

        date  year
0 2024-01-01  2024
1 2024-02-15  2024
2 2024-03-10  2024

In [ ]:
df["month"]=df['date'].dt.month
df

        date  year  month
0 2024-01-01  2024      1
1 2024-02-15  2024      2
2 2024-03-10  2024      3

In [ ]:
df["day_name"]=df["date"].dt.day_name
df

        date  year  month                                           day_name
0 2024-01-01  2024      1  <bound method PandasDelegate._add_delegate_acc...
1 2024-02-15  2024      2  <bound method PandasDelegate._add_delegate_acc...
2 2024-03-10  2024      3  <bound method PandasDelegate._add_delegate_acc...

In [ ]:
df[df['date']>"2024-02-01"]

        date  year  month                                           day_name
1 2024-02-15  2024      2  <bound method PandasDelegate._add_delegate_acc...
2 2024-03-10  2024      3  <bound method PandasDelegate._add_delegate_acc...

In [ ]:
df["next_date"]=df["date"].shift(-1)
df["diff"]=df["next_date"]-df["date"]
df

,date,year,month,day_name,next_date,diff
0,2024-01-01,2024,1,<bound method PandasDelegate._add_delegate_acc...,2024-02-15,45 days
1,2024-02-15,2024,2,<bound method PandasDelegate._add_delegate_acc...,2024-03-10,24 days
2,2024-03-10,2024,3,<bound method PandasDelegate._add_delegate_acc...,NaT,NaT

In [ ]:
df.sort_values("date")

,date,year,month,day_name,next_date,diff
0,2024-01-01,2024,1,<bound method PandasDelegate._add_delegate_acc...,2024-02-15,45 days
1,2024-02-15,2024,2,<bound method PandasDelegate._add_delegate_acc...,2024-03-10,24 days
2,2024-03-10,2024,3,<bound method PandasDelegate._add_delegate_acc...,NaT,NaT

In [ ]:
date={"date":["2024-01-01","2024-01-10","2024-02-05","2024-03-20"]}
df=pd.DataFrame(data)
df

         date
0  2024-01-01
1  2024-02-15
2  2024-03-10

In [ ]:
df['date']=pd.to_datetime(df["date"])
df

        date
0 2024-01-01
1 2024-02-15
2 2024-03-10

In [ ]:
df['year']=df['date'].dt.year
df

        date  year
0 2024-01-01  2024
1 2024-02-15  2024
2 2024-03-10  2024

In [ ]:
df['month']=df["date"].dt.month
df

        date  year  month
0 2024-01-01  2024      1
1 2024-02-15  2024      2
2 2024-03-10  2024      3

In [ ]:
df['day_name']=df['date'].dt.day_name
df

        date  year  month                                           day_name
0 2024-01-01  2024      1  <bound method PandasDelegate._add_delegate_acc...
1 2024-02-15  2024      2  <bound method PandasDelegate._add_delegate_acc...
2 2024-03-10  2024      3  <bound method PandasDelegate._add_delegate_acc...

In [ ]:
df[df['date']>"2024-01-15"]

        date  year  month                                           day_name
1 2024-02-15  2024      2  <bound method PandasDelegate._add_delegate_acc...
2 2024-03-10  2024      3  <bound method PandasDelegate._add_delegate_acc...

In [ ]:
df['next_day']=df['date'].shift(-1)
df['diff']=df["next_day"]-df['date']
df

,date,year,month,day_name,next_day,diff
0,2024-01-01,2024,1,<bound method PandasDelegate._add_delegate_acc...,2024-02-15,45 days
1,2024-02-15,2024,2,<bound method PandasDelegate._add_delegate_acc...,2024-03-10,24 days
2,2024-03-10,2024,3,<bound method PandasDelegate._add_delegate_acc...,NaT,NaT

In [ ]:
import pandas as pd

In [ ]:
s=pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
print(s.name)

None

In [ ]:
s.name="marks"
s

0    10
1    20
2    30
3    40
Name: marks, dtype: int64

In [ ]:
print(s.name)

marks

In [ ]:
s=pd.Series([1,2,3,4,5,"isha"],name="marks")

In [ ]:
s

0       1
1       2
2       3
3       4
4       5
5    isha
Name: marks, dtype: object

In [ ]:
s.values

array([1, 2, 3, 4, 5, 'isha'], dtype=object)

In [ ]:
s.iloc[[1,2,3]]

1    2
2    3
3    4
Name: marks, dtype: object

In [ ]:
s.dtype

dtype('O')

In [ ]:
index=["Uma","Vishwas","Vedik","Jatin","Jayas","Kirtan"]
s.index=index
s

Uma           1
Vishwas       2
Vedik         3
Jatin         4
Jayas         5
Kirtan     isha
Name: marks, dtype: object

In [ ]:
s.loc["Uma":"Vishwas"]

Uma        1
Vishwas    2
Name: marks, dtype: object

In [ ]:
dict1={"name":"isha","dept":"IT","age":25,"salary":10000}

In [ ]:
se=pd.Series(dict1,name="data")
se

name       isha
dept         IT
age          25
salary    10000
Name: data, dtype: object