# Pandas Concepts

pandas Series

pandas series=A series is a one dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.).

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels=['a','b','c']
mylist=[10,20,30]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}
pd.Series(mylist)

0    10
1    20
2    30
dtype: int64

In [3]:
pd.Series(mylist,index=labels)

a    10
b    20
c    30
dtype: int64

In [4]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

data frame

In [6]:
import numpy as np
import pandas as pd

In [7]:
data={
      'Name':["John",'Anna',"Peter","Linda"],
      'Age':[28,32,52,42],
      'Location':['New York','Paris','Berlin','London'],
      "Salary":[6500,7000,6200,8500]
}
df=pd.DataFrame(data)
print(df)

    Name  Age  Location  Salary
0   John   28  New York    6500
1   Anna   32     Paris    7000
2  Peter   52    Berlin    6200
3  Linda   42    London    8500

In [8]:
datalist=[
    ["John",28,"New York",6500],
    ["Anna",32,"Paris",7000],
    ["Peter",52,"Berlin",6200],
    ["Linda",42,"London",8500],
]
df2=pd.DataFrame(datalist)
df2.columns=["Name","Age","Location","Salary"]
print(df2)

    Name  Age  Location  Salary
0   John   28  New York    6500
1   Anna   32     Paris    7000
2  Peter   52    Berlin    6200
3  Linda   42    London    8500

Selection and indexing of columns

In [9]:
df2[["Location","Name"]]

   Location   Name
0  New York   John
1     Paris   Anna
2    Berlin  Peter
3    London  Linda

create a new column

In [10]:
df2["designation"]=["Doctor",'Eng.','Lawyer',"C.A."]

In [11]:
df2

    Name  Age  Location  Salary designation
0   John   28  New York    6500      Doctor
1   Anna   32     Paris    7000        Eng.
2  Peter   52    Berlin    6200      Lawyer
3  Linda   42    London    8500        C.A.

remove a column

In [12]:
df2.drop(["Location","Salary"],axis=1)#it not delete the column permanantly

    Name  Age designation
0   John   28      Doctor
1   Anna   32        Eng.
2  Peter   52      Lawyer
3  Linda   42        C.A.

In [13]:
df2

    Name  Age  Location  Salary designation
0   John   28  New York    6500      Doctor
1   Anna   32     Paris    7000        Eng.
2  Peter   52    Berlin    6200      Lawyer
3  Linda   42    London    8500        C.A.

In [14]:
# datalist=[
#     ["John",28,"New York",6500],
#     ["Anna",32,"Paris",7000],
#     ["Peter",52,"Berlin",6200],
#     ["Linda",42,"London",8500],
# ]
# df2=pd.DataFrame(datalist)
# df2.columns=["Name","Age","Location","Salary"]

# df2["designation"]=["Doctor",'Eng.','Lawyer',"C.A."]

# df2.drop(["Location","Salary"],axis=1,inplace=True)#it delete the column permanantly
# df2

Remove a row

In [15]:
df2.drop(0,axis=0)#it will delete the first row

    Name  Age Location  Salary designation
1   Anna   32    Paris    7000        Eng.
2  Peter   52   Berlin    6200      Lawyer
3  Linda   42   London    8500        C.A.

In [16]:
df2

    Name  Age  Location  Salary designation
0   John   28  New York    6500      Doctor
1   Anna   32     Paris    7000        Eng.
2  Peter   52    Berlin    6200      Lawyer
3  Linda   42    London    8500        C.A.

selecting  a row

In [17]:
df2.loc[[0,1]]#for selecting row we use location(loc)

   Name  Age  Location  Salary designation
0  John   28  New York    6500      Doctor
1  Anna   32     Paris    7000        Eng.

In [18]:
df2

    Name  Age  Location  Salary designation
0   John   28  New York    6500      Doctor
1   Anna   32     Paris    7000        Eng.
2  Peter   52    Berlin    6200      Lawyer
3  Linda   42    London    8500        C.A.

In [19]:
df.iloc[3]

Name         Linda
Age             42
Location    London
Salary        8500
Name: 3, dtype: object

selecting subset of rows and column

In [20]:
df.loc[[2,3]][["Location","Salary"]]

  Location  Salary
2   Berlin    6200
3   London    8500

In [21]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   52
3  Linda   42

Conditional Selection

In [22]:
df2[df2["Age"]>30]#I only want to see people whose age is greater than 30

    Name  Age Location  Salary designation
1   Anna   32    Paris    7000        Eng.
2  Peter   52   Berlin    6200      Lawyer
3  Linda   42   London    8500        C.A.

In [23]:
df2[(df2["Age"]>30) & (df2["Location"]=="Paris")]# I only want to see people whose age is greater than 30 and city is paris

   Name  Age Location  Salary designation
1  Anna   32    Paris    7000        Eng.

Finding missing value

In [24]:
data={
    "A":[1,2,np.nan,4,5],#nan means null value not a number
    "B":[1,2,3,4,5],
    "C":[1,2,3,4,np.nan],
    "D":[1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  4.0  NaN
4  5.0  5  NaN  5.0

In [25]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False  False   True
4  False  False   True  False

In [26]:
df.isna().sum()

A    1
B    0
C    1
D    3
dtype: int64

In [27]:
df.isna().any()#check the columns having null values

A     True
B    False
C     True
D     True
dtype: bool

removing missing values

In [28]:
df.dropna()#it will drop the rows having null values, ye function row k hissab se chlta h

     A  B    C    D
0  1.0  1  1.0  1.0

In [29]:
df.dropna(thresh=3)#minimum three values are not null in row

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
3  4.0  4  4.0  NaN
4  5.0  5  NaN  5.0

filling the missing value

In [30]:
df.fillna(0)#it will replace null values to 0

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  4.0  0.0
4  5.0  5  0.0  5.0

In [31]:
values={'A':0,'B':100,"C":300,"D":400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4    4.0  400.0
4  5.0  5  300.0    5.0

In [32]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  4.0  3.0
4  5.0  5  2.5  5.0

Merging joining and concatanation

In [33]:
employees=pd.DataFrame({
    "employee_id":[1,2,3,7,8],
    "name":["John","Anna","Peter","Linda","Bob"],
    "department":["HR","IT","Finance","IT",'HR']
    })

In [34]:
salaries=pd.DataFrame({"employee_id":[1,2,3,4,5],
                       'salary':[6000,8000,6500,7000,9000],
                       'bonus':[5000,1000,7000,8000,12000]
                       })

In [35]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            7  Linda         IT
4            8    Bob         HR

In [36]:
salaries

   employee_id  salary  bonus
0            1    6000   5000
1            2    8000   1000
2            3    6500   7000
3            4    7000   8000
4            5    9000  12000

In [37]:
pd.merge(employees,salaries,on="employee_id",how="inner")#this will merge the dataframes on the basis of common employee id

   employee_id   name department  salary  bonus
0            1   John         HR    6000   5000
1            2   Anna         IT    8000   1000
2            3  Peter    Finance    6500   7000

In [38]:
pd.merge(employees,salaries,on="employee_id",how="outer")#this will merge the dataframes

   employee_id   name department  salary    bonus
0            1   John         HR  6000.0   5000.0
1            2   Anna         IT  8000.0   1000.0
2            3  Peter    Finance  6500.0   7000.0
3            4    NaN        NaN  7000.0   8000.0
4            5    NaN        NaN  9000.0  12000.0
5            7  Linda         IT     NaN      NaN
6            8    Bob         HR     NaN      NaN

In [39]:
pd.merge(employees,salaries,on="employee_id",how="left")#this will merge the dataframes if names are given

   employee_id   name department  salary   bonus
0            1   John         HR  6000.0  5000.0
1            2   Anna         IT  8000.0  1000.0
2            3  Peter    Finance  6500.0  7000.0
3            7  Linda         IT     NaN     NaN
4            8    Bob         HR     NaN     NaN

In [40]:
pd.merge(employees,salaries,on="employee_id",how="right")#this will merge the dataframes on the basis of salary given

   employee_id   name department  salary  bonus
0            1   John         HR    6000   5000
1            2   Anna         IT    8000   1000
2            3  Peter    Finance    6500   7000
3            4    NaN        NaN    7000   8000
4            5    NaN        NaN    9000  12000

concatination of 2 dataframes

In [73]:
df1=pd.DataFrame({'A':["A0","A1","A2"],
                  'B':["B0","B1","B2"],
                  "C":['C0',"C1","C2"]
                  })
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [74]:
df2=pd.DataFrame({'A':["A3","A4","A5"],
                  'B':["B3","B4","B5"],
                  "C":['C3',"C4","C5"]})
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [75]:
pd.concat([df1,df2])#concate on the basis of column

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [76]:
pd.concat([df1,df2],axis=1)#concate on the basis of row

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [77]:
df1=pd.DataFrame({"name":["Alice","Bob","Charlie"]
                  },index=[1,2,3])
df2=pd.DataFrame({"score":[85,90,75]
                  },index=[2,3,4])

In [46]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [47]:
df2

   score
2     85
3     90
4     75

In [48]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [49]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

Group by aggregation

In [50]:
data={
    "Category":['A','B','A','B','A','B'],
    "Store":['S1','S2','S2','S2','S1','S1'],
    "Sales":[100,150,200,250,300,350],
    "Quantity":[10,15,12,18,8,20],
    "Date":[10,15,12,18,8,20],
}
df=pd.DataFrame(data)
df

  Category Store  Sales  Quantity  Date
0        A    S1    100        10    10
1        B    S2    150        15    15
2        A    S2    200        12    12
3        B    S2    250        18    18
4        A    S1    300         8     8
5        B    S1    350        20    20

In [51]:
#group by category and calculate the sum of sales
df.groupby("Category")['Sales'].sum()

Category
A    600
B    750
Name: Sales, dtype: int64

In [52]:
#group by store and calculate the sum of sales

df.groupby("Store")['Sales'].sum()

Store
S1    750
S2    600
Name: Sales, dtype: int64

In [53]:
#group by multiple columns
#group by category and store
df.groupby(["Category",'Store'])["Sales"].sum()

Category  Store
A         S1       400
          S2       200
B         S1       350
          S2       400
Name: Sales, dtype: int64

Aggregation

In [54]:
df["Sales"].count()
#median,mean,mode,min ,max ,count,std deviation

np.int64(6)

In [55]:
df["Sales"].mode()#it gives full table bcz all values having same number

0    100
1    150
2    200
3    250
4    300
5    350
Name: Sales, dtype: int64

In [56]:
df["Sales"].agg(["mean","median","max"])#mode is not working here bcz it gives full tble if the value of mode is more than one

mean      225.0
median    225.0
max       350.0
Name: Sales, dtype: float64

Pivot tables

In [57]:
data = {
    "Date": pd.date_range("2023-01-01", periods=20),
    "Product": ["A", "B", "C", "D"] * 5,
    "Region": ["East", "West", "North", "South",
               "East", "West", "North", "South",
               "East", "West", "North", "South",
               "East", "West", "North", "South",
               "East", "West", "North", "South"],
    "Sales": np.random.randint(100, 1000, 20),
    "Units": np.random.randint(10, 100, 20),
    "Rep": ["John", "Mary", "Bob", "Alice",
            "John", "Mary", "Bob", "Alice",
            "John", "Mary", "Bob", "Alice",
            "John", "Mary","Bob", "Alice",
            "John", "Mary","Bob", "Alice",]
}
df=pd.DataFrame(data)
df["Month"]=df["Date"].dt.month_name()
df["Quarter"]="Q"+df["Date"].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    914     90   John  January      Q1
1  2023-01-02       B   West    253     78   Mary  January      Q1
2  2023-01-03       C  North    784     98    Bob  January      Q1
3  2023-01-04       D  South    546     24  Alice  January      Q1
4  2023-01-05       A   East    761     54   John  January      Q1
5  2023-01-06       B   West    162     62   Mary  January      Q1
6  2023-01-07       C  North    464     66    Bob  January      Q1
7  2023-01-08       D  South    451     94  Alice  January      Q1
8  2023-01-09       A   East    417     17   John  January      Q1
9  2023-01-10       B   West    670     40   Mary  January      Q1
10 2023-01-11       C  North    781     69    Bob  January      Q1
11 2023-01-12       D  South    725     40  Alice  January      Q1
12 2023-01-13       A   East    152     83   John  January      Q1
13 2023-01-14       B   West    832     88   Mary  January      Q1
14 2023-01-15       C  North    880     31    Bob  January      Q1
15 2023-01-16       D  South    332     63  Alice  January      Q1
16 2023-01-17       A   East    915     18   John  January      Q1
17 2023-01-18       B   West    147     84   Mary  January      Q1
18 2023-01-19       C  North    150     40    Bob  January      Q1
19 2023-01-20       D  South    790     66  Alice  January      Q1

In [58]:
pd.pivot_table(df,values='Sales',index="Region",columns="Product",aggfunc="median")#default aggregation function is mean

Product      A      B      C      D
Region
East     761.0    NaN    NaN    NaN
North      NaN    NaN  781.0    NaN
South      NaN    NaN    NaN  546.0
West       NaN  253.0    NaN    NaN

In [59]:
pivot=pd.pivot_table(df,values=["Sales","Units"],index="Region",columns="Product")
pivot#values must be numeric

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     631.8    NaN    NaN    NaN  52.4   NaN   NaN   NaN
North      NaN    NaN  611.8    NaN   NaN   NaN  60.8   NaN
South      NaN    NaN    NaN  568.8   NaN   NaN   NaN  57.4
West       NaN  412.8    NaN    NaN   NaN  70.4   NaN   NaN

cross tab

In [60]:
pd.crosstab(df["Region"],df["Product"])#defaultly gives count

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

operations

In [61]:
df1=pd.DataFrame({
    "A":[1,2,3,4,5],
    "B":[10,20,30,40,50],
    "C":[100,200,300,400,500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [62]:
df1.shape

(5, 3)

In [63]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [64]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [65]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [66]:
df1["A"]+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [67]:
def square(x):
  return x**2

In [68]:
df1["B"].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [69]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [70]:
df1["D"]=df1["B"].apply(square)

In [71]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

In [ ]:
copy_df.insert(2,City)