# NumPy + Pandas Practice

In [1]:
import pandas as pd
import numpy as np

### STUDENTS INFO

In [2]:
data={'Name':["A","B",'C','D',"E",'F','G','H'],
      'Maths':[80,90,np.nan,70,60,85,90,np.nan],
      'Science':[75,85,80,np.nan,65,88,92,70],
      "English":[70,80,75,60,np.nan,82,85,78],
      "City":["Delhi",'Mumbai',"Delhi",'Mumbai',"Delhi","Pune",'Delhi',"Indore"]
      }
df=pd.DataFrame(data)
print(df)

  Name  Maths  Science  English    City
0    A   80.0     75.0     70.0   Delhi
1    B   90.0     85.0     80.0  Mumbai
2    C    NaN     80.0     75.0   Delhi
3    D   70.0      NaN     60.0  Mumbai
4    E   60.0     65.0      NaN   Delhi
5    F   85.0     88.0     82.0    Pune
6    G   90.0     92.0     85.0   Delhi
7    H    NaN     70.0     78.0  Indore

In [3]:
print(df.head())
print(df.info())
print(df.describe())

  Name  Maths  Science  English    City
0    A   80.0     75.0     70.0   Delhi
1    B   90.0     85.0     80.0  Mumbai
2    C    NaN     80.0     75.0   Delhi
3    D   70.0      NaN     60.0  Mumbai
4    E   60.0     65.0      NaN   Delhi
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     8 non-null      str
 1   Maths    6 non-null      float64
 2   Science  7 non-null      float64
 3   English  7 non-null      float64
 4   City     8 non-null      str
dtypes: float64(3), str(2)
memory usage: 502.0 bytes
None
           Maths    Science    English
count   6.000000   7.000000   7.000000
mean   79.166667  79.285714  75.714286
std    12.006942   9.827076   8.459990
min    60.000000  65.000000  60.000000
25%    72.500000  72.500000  72.500000
50%    82.500000  80.000000  78.000000
75%    88.750000  86.500000  81.000000
max    90.000000  92.000000  85.000000

In [4]:
df['Maths']=df['Maths'].fillna(df["Maths"].mean())
df['English']=df['English'].fillna(df["English"].mean())
df["Science"]=df["Science"].fillna(df['Science'].mean())
df['Total']=df['Maths']+df["Science"]+df["English"]

In [5]:
df['Average'] = df[["Maths","Science","English"]].mean(axis=1)
df

  Name      Maths    Science    English    City       Total    Average
0    A  80.000000  75.000000  70.000000   Delhi  225.000000  75.000000
1    B  90.000000  85.000000  80.000000  Mumbai  255.000000  85.000000
2    C  79.166667  80.000000  75.000000   Delhi  234.166667  78.055556
3    D  70.000000  79.285714  60.000000  Mumbai  209.285714  69.761905
4    E  60.000000  65.000000  75.714286   Delhi  200.714286  66.904762
5    F  85.000000  88.000000  82.000000    Pune  255.000000  85.000000
6    G  90.000000  92.000000  85.000000   Delhi  267.000000  89.000000
7    H  79.166667  70.000000  78.000000  Indore  227.166667  75.722222

In [6]:
df['Grade']=df['Average'].apply(lambda x: 'A' if x>=85 else ('B' if x>=70 else 'C'))

In [7]:
print(df.groupby('City')['Average'].mean())

City
Delhi     77.240079
Indore    75.722222
Mumbai    77.380952
Pune      85.000000
Name: Average, dtype: float64

In [8]:
print(df.sort_values("Average",ascending=False).head(1))

  Name  Maths  Science  English   City  Total  Average Grade
6    G   90.0     92.0     85.0  Delhi  267.0     89.0     A

In [9]:
print(df[df['Average']>80])

  Name  Maths  Science  English    City  Total  Average Grade
1    B   90.0     85.0     80.0  Mumbai  255.0     85.0     A
5    F   85.0     88.0     82.0    Pune  255.0     85.0     A
6    G   90.0     92.0     85.0   Delhi  267.0     89.0     A

In [10]:
arr=df[["Maths","Science","English"]]
print(arr)

       Maths    Science    English
0  80.000000  75.000000  70.000000
1  90.000000  85.000000  80.000000
2  79.166667  80.000000  75.000000
3  70.000000  79.285714  60.000000
4  60.000000  65.000000  75.714286
5  85.000000  88.000000  82.000000
6  90.000000  92.000000  85.000000
7  79.166667  70.000000  78.000000

In [11]:
print(np.mean(arr))

78.05555555555556

In [12]:
print(np.max(arr,axis=0))

Maths      90.0
Science    92.0
English    85.0
dtype: float64

In [13]:
df.sort_values("Average",ascending=False).tail(1)

  Name  Maths  Science    English   City       Total    Average Grade
4    E   60.0     65.0  75.714286  Delhi  200.714286  66.904762     C

In [14]:
df.groupby('City')["Average"].mean().idxmax()

'Pune'

In [15]:
df["pass/fail"]=df['Average'].apply(lambda x: "pass" if x>=70  else "fail")
df

,Name,Maths,Science,English,City,Total,Average,Grade,pass/fail
0,A,80.000000,75.000000,70.000000,Delhi,225.000000,75.000000,B,pass
1,B,90.000000,85.000000,80.000000,Mumbai,255.000000,85.000000,A,pass
2,C,79.166667,80.000000,75.000000,Delhi,234.166667,78.055556,B,pass
3,D,70.000000,79.285714,60.000000,Mumbai,209.285714,69.761905,C,fail
4,E,60.000000,65.000000,75.714286,Delhi,200.714286,66.904762,C,fail
5,F,85.000000,88.000000,82.000000,Pune,255.000000,85.000000,A,pass
6,G,90.000000,92.000000,85.000000,Delhi,267.000000,89.000000,A,pass
7,H,79.166667,70.000000,78.000000,Indore,227.166667,75.722222,B,pass

In [16]:
df[["Maths","Science","English"]].corr()

            Maths   Science   English
Maths    1.000000  0.805716  0.580507
Science  0.805716  1.000000  0.401108
English  0.580507  0.401108  1.000000

In [17]:
corr=df.select_dtypes(include="number").corr()["Average"]

In [18]:
corr = df.select_dtypes(include='number').corr()

f=corr["Average"].sort_values(ascending=False)

In [19]:
pd.DataFrame(f)
f
print(f[f<1].head(1))

Maths    0.943171
Name: Average, dtype: float64

### EMPLOYEE INFO

In [20]:
data={"Name":['A','B','C','D','E','F','G','H'],
      "Age":[25,30,35,40,28,32,38,29],
      "Department":['IT',"HR",'IT','FINAL','HR','IT','FINANCE','HR'],
      'Salary':[50000,60000,np.nan,80000,55000,62000,np.nan,58000],
      "Experience":[2,5,8,10,3,6,9,4]
      }
df=pd.DataFrame(data)
print(df)

  Name  Age Department   Salary  Experience
0    A   25         IT  50000.0           2
1    B   30         HR  60000.0           5
2    C   35         IT      NaN           8
3    D   40      FINAL  80000.0          10
4    E   28         HR  55000.0           3
5    F   32         IT  62000.0           6
6    G   38    FINANCE      NaN           9
7    H   29         HR  58000.0           4

In [21]:
df['Salary']=df["Salary"].fillna(df['Salary'].mean())

In [22]:
df["NewSalary"]=df['Salary']+10000
df

  Name  Age Department        Salary  Experience     NewSalary
0    A   25         IT  50000.000000           2  60000.000000
1    B   30         HR  60000.000000           5  70000.000000
2    C   35         IT  60833.333333           8  70833.333333
3    D   40      FINAL  80000.000000          10  90000.000000
4    E   28         HR  55000.000000           3  65000.000000
5    F   32         IT  62000.000000           6  72000.000000
6    G   38    FINANCE  60833.333333           9  70833.333333
7    H   29         HR  58000.000000           4  68000.000000

In [23]:
df['level']=df['Experience'].apply(lambda x:'junior' if x<=5  else ("Intermediate" if x<=8 else "senior" ))
df

  Name  Age Department        Salary  Experience     NewSalary         level
0    A   25         IT  50000.000000           2  60000.000000        junior
1    B   30         HR  60000.000000           5  70000.000000        junior
2    C   35         IT  60833.333333           8  70833.333333  Intermediate
3    D   40      FINAL  80000.000000          10  90000.000000        senior
4    E   28         HR  55000.000000           3  65000.000000        junior
5    F   32         IT  62000.000000           6  72000.000000  Intermediate
6    G   38    FINANCE  60833.333333           9  70833.333333        senior
7    H   29         HR  58000.000000           4  68000.000000        junior

In [24]:
df.groupby('Department')["Salary"].mean()

Department
FINAL      80000.000000
FINANCE    60833.333333
HR         57666.666667
IT         57611.111111
Name: Salary, dtype: float64

In [25]:
df.sort_values("Salary",ascending=False).head(1)

  Name  Age Department   Salary  Experience  NewSalary   level
3    D   40      FINAL  80000.0          10    90000.0  senior

In [26]:
df["Department"].value_counts()

Department
IT         3
HR         3
FINAL      1
FINANCE    1
Name: count, dtype: int64

In [27]:
a=df["Salary"].values
a

array([50000.        , 60000.        , 60833.33333333, 80000.        ,
       55000.        , 62000.        , 60833.33333333, 58000.        ])

In [28]:
np.mean(a)

np.float64(60833.333333333336)

In [29]:
np.std(a)

np.float64(8130.4468921865955)

In [30]:
np.max(a)

np.float64(80000.0)

In [31]:
np.min(a)

np.float64(50000.0)

In [32]:
df[(df["Salary"]>6000) &(df["Experience"]>5)]

  Name  Age Department        Salary  Experience     NewSalary         level
2    C   35         IT  60833.333333           8  70833.333333  Intermediate
3    D   40      FINAL  80000.000000          10  90000.000000        senior
5    F   32         IT  62000.000000           6  72000.000000  Intermediate
6    G   38    FINANCE  60833.333333           9  70833.333333        senior

In [33]:
df.corr(numeric_only=True)["Salary"].drop("Salary").sort_values(ascending=False)

NewSalary     1.000000
Age           0.835545
Experience    0.816089
Name: Salary, dtype: float64

In [34]:
df.sort_values("Salary").head(1)

  Name  Age Department   Salary  Experience  NewSalary   level
0    A   25         IT  50000.0           2    60000.0  junior

In [35]:
df.groupby("Department")["Salary"].mean().reset_index().max()

Department         IT
Salary        80000.0
dtype: object

In [36]:
df[df["Salary"]>df["Salary"].mean()]

  Name  Age Department   Salary  Experience  NewSalary         level
3    D   40      FINAL  80000.0          10    90000.0        senior
5    F   32         IT  62000.0           6    72000.0  Intermediate

In [37]:
df["Salary"].mean()

np.float64(60833.333333333336)

In [38]:
df["Bonus"]=df["Salary"]*1.2
df

,Name,Age,Department,Salary,Experience,NewSalary,level,Bonus
0,A,25,IT,50000.000000,2,60000.000000,junior,60000.0
1,B,30,HR,60000.000000,5,70000.000000,junior,72000.0
2,C,35,IT,60833.333333,8,70833.333333,Intermediate,73000.0
3,D,40,FINAL,80000.000000,10,90000.000000,senior,96000.0
4,E,28,HR,55000.000000,3,65000.000000,junior,66000.0
5,F,32,IT,62000.000000,6,72000.000000,Intermediate,74400.0
6,G,38,FINANCE,60833.333333,9,70833.333333,senior,73000.0
7,H,29,HR,58000.000000,4,68000.000000,junior,69600.0